### ISSUE TITLE
`KeyError: 'items'` on `qualitube` shell command

### ISSUE THREAD

**Issue by bitterteriyaki** [vmussa/qualitube#1]
When I type `qualitube` on shell terminal, I get this following exception:
```
INFO:root:Beginning of pipeline.
Traceback (most recent call last):
  File "/home/.../.venv/bin/qualitube", line 8, in <module>
    sys.exit(main())
  File "/home/.../qualitube/main.py", line 34, in main
    dfs = [playlist.to_df() for playlist in playlists]
  File "/home/.../qualitube/main.py", line 34, in <listcomp>
    dfs = [playlist.to_df() for playlist in playlists]
  File "/home/.../playlist_items.py", line 73, in to_df
    data = self.get_playlist_items_data()
  File "/home/.../qualitube/playlist_items.py", line 65, in get_playlist_items_data
    videos_data, next_page_token = self._parse_response(r.text)
  File "/home/.../qualitube/playlist_items.py", line 24, in _parse_response
    items = raw["items"]
KeyError: 'items'
```

This is my `config.ini`:
```ini
[credentials]
api_key=<My API Key>

[channels]
ids=
    PLdnY_glW0R2iIdYBNy9IhmHOuaS-NBo40
```

**Comment by vmussa** [comment]
This is strange @soukyomi. Here it works well. Are you sure you have set up your Youtube API v3 key correctly? You are probably getting empty results from the API because of an error response. If that is the case, the API would give you this JSON response: `{'error': {'code': 400, 'message': 'API key not valid. Please pass a valid API key.', 'errors': [{'message': 'API key not valid. Please pass a valid API key.', 'domain': 'global', 'reason': 'badRequest'}], 'status': 'INVALID_ARGUMENT'}}`. I will add a `raise` with a custom Exception in that case for a better traceback, then I will contact you back so you can update your installation and be better informed of the error that is going on. Thank you for submitting this issue.

If you want, you can also add a `print(raw)` statement at line 23 in `playlist_items.py` and use it with poetry, so that you can read the API's response and get more info.

My output:
```
INFO:root:Beginning of pipeline.
INFO:root:Got PlaylistItem -> id: UExkbllfZ2xXMFIyaUlkWUJOeTlJaG1IT3VhUy1OQm80MC4yODlGNEE0NkRGMEEzMEQy / title: AULA 01: HIRAGANA (Alfabeto Japonês)
INFO:root:Got PlaylistItem -> id: UExkbllfZ2xXMFIyaUlkWUJOeTlJaG1IT3VhUy1OQm80MC4wMTcyMDhGQUE4NTIzM0Y5 / title: AULA 02: Como se apresentar
INFO:root:Got PlaylistItem -> id: UExkbllfZ2xXMFIyaUlkWUJOeTlJaG1IT3VhUy1OQm80MC41MjE1MkI0OTQ2QzJGNzNG / title: AULA 03: Como ler o KATAKANA
INFO:root:Got PlaylistItem -> id: UExkbllfZ2xXMFIyaUlkWUJOeTlJaG1IT3VhUy1OQm80MC4wOTA3OTZBNzVEMTUzOTMy / title: AULA 04: Como aprender o Kanji
INFO:root:Got PlaylistItem -> id: UExkbllfZ2xXMFIyaUlkWUJOeTlJaG1IT3VhUy1OQm80MC4xMkVGQjNCMUM1N0RFNEUx / title: AULA 05: Como fazer perguntas em Japonês
INFO:root:Got PlaylistItem -> id: UExkbllfZ2xXMFIyaUlkWUJOeTlJaG1IT3VhUy1OQm80MC41MzJCQjBCNDIyRkJDN0VD / title: AULA 06: Como demonstrar
INFO:root:Got PlaylistItem -> id: UExkbllfZ2xXMFIyaUlkWUJOeTlJaG1IT3VhUy1OQm80MC5DQUNERDQ2NkIzRUQxNTY1 / title: AULA 07: Como usar o dicionário Japonês
INFO:root:Got PlaylistItem -> id: UExkbllfZ2xXMFIyaUlkWUJOeTlJaG1IT3VhUy1OQm80MC45NDk1REZENzhEMzU5MDQz / title: AULA 08: Expressões de cortesia
INFO:root:Got PlaylistItem -> id: UExkbllfZ2xXMFIyaUlkWUJOeTlJaG1IT3VhUy1OQm80MC5GNjNDRDREMDQxOThCMDQ2 / title: AULA 09: Habilidades para aprender Japonês
INFO:root:Got PlaylistItem -> id: UExkbllfZ2xXMFIyaUlkWUJOeTlJaG1IT3VhUy1OQm80MC40NzZCMERDMjVEN0RFRThB / title: AULA 10: Como expressar o que gosta?
INFO:root:Got PlaylistItem -> id: UExkbllfZ2xXMFIyaUlkWUJOeTlJaG1IT3VhUy1OQm80MC5EMEEwRUY5M0RDRTU3NDJC / title: AULA 11: Aprender japonês (Revisão e Conclusão)
INFO:root:Got Video -> id: C3Cn3G4ia00 title: AULA 01: HIRAGANA (Alfabeto Japonês)
INFO:root:Got Video -> id: PoDzqFlpG_o title: AULA 02: Como se apresentar
INFO:root:Got Video -> id: d9BpFHwBmw4 title: AULA 03: Como ler o KATAKANA
INFO:root:Got Video -> id: aCvnuPp566A title: AULA 04: Como aprender o Kanji
INFO:root:Got Video -> id: INBLuZ0NNRY title: AULA 05: Como fazer perguntas em Japonês
INFO:root:Got Video -> id: iCQvSE0Gl8A title: AULA 06: Como demonstrar
INFO:root:Got Video -> id: bvOjpgfUWYE title: AULA 07: Como usar o dicionário Japonês
INFO:root:Got Video -> id: NBASXfL58ng title: AULA 08: Expressões de cortesia
INFO:root:Got Video -> id: 3bAfbBaAz7I title: AULA 09: Habilidades para aprender Japonês
INFO:root:Got Video -> id: wG-9pQbQAKY title: AULA 10: Como expressar o que gosta?
INFO:root:Got Video -> id: GFgUn8yVw9w title: AULA 11: Aprender japonês (Revisão e Conclusão)
INFO:root:End of pipeline.
```

**Comment by vmussa** [comment]
@soukyomi I've just updated `qualitube` in PyPI. Please run a `pip install -U qualitube` to get the latest version that raises an `Exception` in case of an error response. I will ask you another favor, if it is ok: please report back to me at https://github.com/LABHDUFBA/qualitube/ if you need. You can open another issue there if you want. That is the official qualitube's repo now. Thanks again and sorry for the mess :)

**Comment by soukyomi** [comment]
Hello user. Thanks for the quick response and thanks for the help. I updated Qualitube and ran a new test and this was the error I got:
```py
{
    "error": {
        "code": 403,
        "message": "YouTube Data API v3 has not been used in project <Project ID> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=<Project ID> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
        "errors": [
            {
                "message": "YouTube Data API v3 has not been used in project <Project ID> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=<Project ID> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
                "domain": "usageLimits",
                "reason": "accessNotConfigured",
                "extendedHelp": "https://console.developers.google.com",
            }
        ],
        "status": "PERMISSION_DENIED",
    }
}
```
What appears to be a configuration error on my part. If I have new problems I will report them to the new repository. Again, thanks for the help!

**Comment by bitterteriyaki** [comment]
Hello @vmussa. Thanks for the quick response and thanks for the help. I updated Qualitube and ran a new test and this was the error I got:
```py
{
    "error": {
        "code": 403,
        "message": "YouTube Data API v3 has not been used in project <Project ID> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=<Project ID> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
        "errors": [
            {
                "message": "YouTube Data API v3 has not been used in project <Project ID> before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/youtube.googleapis.com/overview?project=<Project ID> then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
                "domain": "usageLimits",
                "reason": "accessNotConfigured",
                "extendedHelp": "https://console.developers.google.com",
            }
        ],
        "status": "PERMISSION_DENIED",
    }
}
```
What appears to be a configuration error on my part 🤦. If I have new problems I will report them to the new repository. Again, thanks for the help!

**Update:** I fixed the issue. Working perfectly now.
